logging:
  level:
    com.tencent: debug
devops:
  logging:
    path: D://
    app-file: sample.log
    error-file: sample-error.log
  loadbalancer:
    gray:
      enabled: true
      meta-key: env
    local-prior:
      enabled: true

